export enum NavigationEnum{
    LOGIN = '/login',
    DASHBOARD = '/dashboard',
    LISTAR_CLIENTES = '/clientes',
    ADICIONAR_CLIENTES = '/clientes/novo',
    EDITAR_CLIENTES = '/clientes/editar/',
    LISTAR_PRESTADORES = '/prestadores',
    ADICIONAR_PRESTADORES = '/prestadores/novo',
    EDITAR_PRESTADORES = '/prestadores/editar/',
    LISTAR_OCORRENCIAS = '/ocorrencias',
    NOVA_OCORRENCIA = '/ocorrencias/nova',
    LISTAR_USUARIOS = '/usuarios',
    ADICIONAR_USUARIOS = '/usuarios/novo',
    EDITAR_USUARIOS = '/usuarios/editar/',
    NAO_AUTORIZADO = '/nao-autorizado',
}